version: '3.8'

services:
  # Laravel APIサービス
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ../backend:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - app-network

  # Next.jsフロントエンドサービス
  nextjs:
    build:
      context: .
      dockerfile: nextjs/Dockerfile
    volumes:
      - ../frontend:/app
      # node_modulesをボリュームとして管理
      - nextjs_node_modules:/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - TINI_SUBREAPER=true
    networks:
      - app-network
    init: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  # MySQLサービス
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    networks:
      - app-network

  # テスト実行環境
  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    volumes:
      - ../backend:/var/www/html
      - ../frontend:/app
    depends_on:
      - laravel
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  nextjs_node_modules:
    driver: local

networks:
  app-network:
    driver: bridge 